FROM debian:jessie

# persistent / runtime deps
RUN apt-get update && apt-get install -y ca-certificates curl libxml2 --no-install-recommends && rm -r /var/lib/apt/lists/*

# phpize deps
RUN apt-get update && apt-get install -y autoconf file gcc libc-dev make pkg-config re2c --no-install-recommends && rm -r /var/lib/apt/lists/*

ENV PHP_INI_DIR /usr/local/etc/php
RUN mkdir -p $PHP_INI_DIR/conf.d

##<autogenerated>##
RUN apt-get update && apt-get install -y apache2-bin apache2.2-common --no-install-recommends && rm -rf /var/lib/apt/lists/*

RUN rm -rf /var/www/html && mkdir -p /var/lock/apache2 /var/run/apache2 /var/log/apache2 /var/www/html && chown -R www-data:www-data /var/lock/apache2 /var/run/apache2 /var/log/apache2 /var/www/html

# Apache + PHP requires preforking Apache for best results
RUN a2dismod mpm_event && a2enmod mpm_prefork

RUN mkdir -p /etc/apache2/certs/ && mkdir -p /etc/apache2/vhosts/
RUN mv /etc/apache2/apache2.conf /etc/apache2/apache2.conf.dist && rm /etc/apache2/conf-enabled/* /etc/apache2/sites-enabled/*
COPY apache2.conf /etc/apache2/apache2.conf
# it'd be nice if we could not COPY apache2.conf until the end of the Dockerfile, but its contents are checked by PHP during compilation

ENV PHP_EXTRA_BUILD_DEPS apache2-dev
ENV PHP_EXTRA_CONFIGURE_ARGS --with-apxs2
##</autogenerated>##

RUN gpg --keyserver pool.sks-keyservers.net --recv-keys F38252826ACD957EF380D39F2F7956BC5DA04B5D

ENV PHP_VERSION 5.3.28

# --enable-mysqlnd is included below because it's harder to compile after the fact the extensions are (since it's a plugin for several extensions, not an extension in itself)
RUN buildDeps=" \
		$PHP_EXTRA_BUILD_DEPS \
		bzip2 \
		libcurl4-openssl-dev \
		libreadline6-dev \
		libssl-dev \
		libxml2-dev \
	" \
	&& set -x \
	&& apt-get update && apt-get install -y $buildDeps --no-install-recommends && rm -rf /var/lib/apt/lists/* \
	&& curl -SL "http://php.net/get/php-$PHP_VERSION.tar.bz2/from/this/mirror" -o php.tar.bz2 \
	&& curl -SL "http://php.net/get/php-$PHP_VERSION.tar.bz2.asc/from/this/mirror" -o php.tar.bz2.asc \
	&& gpg --verify php.tar.bz2.asc \
	&& mkdir -p /usr/src/php \
	&& tar -xof php.tar.bz2 -C /usr/src/php --strip-components=1 \
	&& rm php.tar.bz2* \
	&& cd /usr/src/php \
	&& ./configure \
		--with-config-file-path="$PHP_INI_DIR" \
		--with-config-file-scan-dir="$PHP_INI_DIR/conf.d" \
		$PHP_EXTRA_CONFIGURE_ARGS \
		--disable-cgi \
		--enable-mysqlnd \
		--with-curl \
		--with-openssl \
		--with-readline \
		--with-zlib \
	&& make -j"$(nproc)" \
	&& make install \
	&& { find /usr/local/bin /usr/local/sbin -type f -executable -exec strip --strip-all '{}' + || true; } \
	&& apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false -o APT::AutoRemove::SuggestsImportant=false $buildDeps \
	&& make clean

COPY docker-php-ext-* /usr/local/bin/

##<autogenerated>##
COPY apache2-foreground /usr/local/bin/
WORKDIR /var/www/html

EXPOSE 80
CMD ["apache2-foreground"]
##</autogenerated>##

RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng12-dev \
        zlib1g-dev \
        git \
        wget \
    && docker-php-ext-install iconv mcrypt \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install gd \
    && docker-php-ext-install pdo pdo_mysql \
    && docker-php-ext-install mysql \
    && docker-php-ext-install mbstring \
    && docker-php-ext-install zip

RUN a2enmod headers
RUN a2enmod expires
RUN a2enmod ssl
RUN a2enmod rewrite

RUN /usr/local/bin/pecl install --force memcache
RUN echo 'extension=memcache.so' >> /usr/local/etc/php/conf.d/memcache.ini

#Install PHPUnit
#RUN wget https://phar.phpunit.de/phpunit.phar \
#    && chmod +x phpunit.phar \
#    && mv phpunit.phar /usr/local/bin/phpunit
    
#Install Composer
#RUN curl -sS https://getcomposer.org/installer | php \
#        && mv composer.phar /usr/local/bin/

RUN mkdir -p /usr/local/www/data-dist && \
	mkdir -p /usr/local/www/app-dist && \
	mkdir -p /usr/local/www/workcopy && \
	mkdir -p /var/www/html/workcopy && \
	mkdir -p /var/www/html/personareyii && \
	mkdir -p /var/www/html/phpbb && \
	mkdir -p /var/www/html/admin && \
	mkdir -p /var/www/html/yiicore && \
	mkdir -p /var/www/html/portal-client

RUN ln -sFf /var/www/html/workcopy /usr/local/www/data-dist/workcopy  && \
	ln -sFf /var/www/html/personareyii /usr/local/www/data-dist/personareyii  && \
	ln -sFf /var/www/html/admin /usr/local/www/data-dist/admin  && \
	ln -sFf /var/www/html/yiicore /usr/local/www/data-dist/yiicore  && \
	ln -sFf /var/www/html/portal-client /usr/local/www/workcopy/portal-client && \
	ln -sFf /var/www/html/phpbb /usr/local/www/app-dist/phpbb

RUN chown -R www-data:www-data /var/www/html && \
	chown -R www-data:www-data /usr/local/www/
